apiVersion: apps/v1
kind: Deployment
metadata:
  name: tiny-app
  labels:
    app: tiny-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tiny-app
  template:
    metadata:
      labels:
        app: tiny-app
    spec:
      containers:
      - name: tiny-app
        image: adhomi/tiny-java-frontend-backend:v2
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
        env:
          - name: IETS_VAN_DEFAULT_PASSWORD
            value: wachtwoord
          - name: IETS_VAN_DEFAULT_EMAIL
            value: beni@qualityaccelerators.nl
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: tiny-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tiny-app
  minReplicas: 1
  maxReplicas: 8
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100
        periodSeconds: 10
      - type: Pods
        value: 4
        periodSeconds: 10
    scaleDown:
      stabilizationWindowSeconds: 10
      policies:
      - type: Percent
        value: 100
        periodSeconds: 10
      - type: Pods
        value: 4
        periodSeconds: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 100
